# Generated by Django 3.2.8 on 2021-11-12 12:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='os_type',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='download_urls',
            field=models.JSONField(default=list, verbose_name='Download URLS'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='datastore',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='datastore',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='manageditem',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='manageditem',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='osedition',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osedition',
            name='os_edition_type',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('APPLE', 'Apple'), ('LINUX', 'Linux'), ('BSD', 'BSD'), ('VMWARE', 'VMware'), ('STORAGE', 'Storage Appliances'), ('VIRTUALIZATION', 'Virtualization Appliances'), ('FIREWALL', 'Firewall Appliances'), ('FIRMWARE', 'Firmware and driver utilities'), ('RECOVERY', 'Recovery Tools'), ('OTHER', 'Other')], default='LINUX', help_text='The type of image', max_length=16, verbose_name='OS Type'),
        ),
        migrations.AddField(
            model_name='osedition',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='remotecatalog',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='remotecatalog',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AddField(
            model_name='updatetarget',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='updatetarget',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated Time'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='os_edition',
            field=models.ForeignKey(blank=True, help_text='The edition of the OS', max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='isomanager.osedition'),
        ),
        migrations.AlterField(
            model_name='osedition',
            name='os_edition_arch',
            field=models.CharField(choices=[('X86', 'x86'), ('AMD64', 'amd64'), ('ARMV8', 'ArmV8'), ('DARWIN_ARM64', 'darwin_arm64')], default='AMD64', help_text='The architecture of the OS', max_length=16, verbose_name='OS Architecture'),
        ),
        migrations.AlterField(
            model_name='osedition',
            name='os_edition_language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('FRENCH', 'French')], help_text='The language of the item in the catalog', max_length=64, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='osedition',
            name='os_edition_name',
            field=models.CharField(help_text='The edition of the OS', max_length=32, verbose_name='OS Edition'),
        ),
        migrations.AlterField(
            model_name='osedition',
            name='os_edition_version',
            field=models.CharField(help_text='The version number of the item', max_length=32, verbose_name='Version Number'),
        ),
    ]
