# Generated by Django 3.2.8 on 2021-10-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryitem',
            name='localname',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
