# Generated by Django 3.2.8 on 2021-10-20 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0002_libraryitem_localname'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastore',
            name='location',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
