# Generated by Django 3.2.8 on 2021-10-20 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0003_datastore_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='datastoretype',
            field=models.CharField(choices=[('PATH', 'Path'), ('SSH', 'Ssh'), ('FTP', 'Ftp')], default='PATH', max_length=4),
        ),
        migrations.AlterField(
            model_name='datastore',
            name='last_scan',
            field=models.DateTimeField(blank=True, verbose_name='last scan'),
        ),
    ]
