# Generated by Django 3.2.8 on 2021-11-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0003_auto_20211115_0826'),
    ]

    operations = [
        migrations.AddField(
            model_name='osedition',
            name='os_edition_description',
            field=models.CharField(default='aaa', help_text='Description of the OS', max_length=32, verbose_name='OS description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='osedition',
            name='os_edition_version_scheme',
            field=models.CharField(default='aaa', help_text='The version scheme of the OS', max_length=32, verbose_name='OS Version Scheme'),
            preserve_default=False,
        ),
    ]
