# Generated by Django 3.2.8 on 2021-11-15 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0004_auto_20211115_0832'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='sha256sumgpg',
            new_name='sha256sum_gpg',
        ),
    ]
