# Generated by Django 3.2.8 on 2021-10-20 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0004_auto_20211020_0258'),
    ]

    operations = [
        migrations.RenameField(
            model_name='libraryitem',
            old_name='localname',
            new_name='local_name',
        ),
        migrations.RenameField(
            model_name='localcatalog',
            old_name='detachedfromhead',
            new_name='detached_from_head',
        ),
        migrations.RenameField(
            model_name='localcatalog',
            old_name='ostype',
            new_name='os_type',
        ),
        migrations.RemoveField(
            model_name='datastore',
            name='datastoretype',
        ),
        migrations.RemoveField(
            model_name='localcatalog',
            name='versionscheme',
        ),
        migrations.AddField(
            model_name='datastore',
            name='datastore_type',
            field=models.CharField(choices=[('PATH', 'Path'), ('SSH', 'Ssh')], default='PATH', max_length=4),
        ),
        migrations.AddField(
            model_name='localcatalog',
            name='version_scheme',
            field=models.CharField(choices=[('SEM', 'SemVer'), ('CAL', 'CalVer')], default='SEM', help_text='The version scheme being used', max_length=3, verbose_name='version scheme'),
        ),
        migrations.AlterField(
            model_name='localcatalog',
            name='last_update',
            field=models.DateTimeField(help_text='Time last scanned', verbose_name='last update'),
        ),
    ]
