# Generated by Django 3.2.8 on 2021-11-15 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0005_rename_sha256sumgpg_catalogitem_sha256sum_gpg'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='os_edition',
            field=models.ForeignKey(blank=True, help_text='The edition of the OS', max_length=32, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='isomanager.osedition'),
        ),
    ]
