# Generated by Django 3.2.8 on 2021-10-20 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0006_alter_datastore_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastore',
            name='last_scan',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last scan'),
        ),
    ]
