# Generated by Django 3.2.8 on 2021-11-15 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0006_catalogitem_os_edition'),
    ]

    operations = [
        migrations.AddField(
            model_name='catalogitem',
            name='catalog',
            field=models.ForeignKey(blank=True, help_text='Remote Catalog', null=True, on_delete=django.db.models.deletion.CASCADE, to='isomanager.remotecatalog'),
        ),
    ]
