# Generated by Django 3.2.8 on 2021-11-16 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0007_catalogitem_catalog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='catalog',
        ),
    ]
