# Generated by Django 3.2.8 on 2021-10-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0007_alter_datastore_last_scan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='localcatalog',
            name='version',
            field=models.CharField(help_text='The version number of the item', max_length=255, verbose_name='version number'),
        ),
    ]
