# Generated by Django 3.2.8 on 2021-11-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0008_remove_catalogitem_catalog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='language',
            new_name='os_language',
        ),
        migrations.RenameField(
            model_name='catalogitem',
            old_name='version',
            new_name='os_version',
        ),
        migrations.RenameField(
            model_name='catalogitem',
            old_name='version_scheme',
            new_name='os_version_scheme',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='os_description',
            field=models.CharField(blank=True, help_text='Item description', max_length=100, null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='description',
            field=models.CharField(blank=True, help_text='Item description', max_length=100, null=True, verbose_name='Description'),
        ),
    ]
