# Generated by Django 3.2.8 on 2021-11-16 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0009_auto_20211116_1014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='os_description',
            field=models.CharField(blank=True, help_text='OS description', max_length=100, null=True, verbose_name='OS Description'),
        ),
    ]
