# Generated by Django 3.2.8 on 2021-11-16 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0010_alter_catalogitem_os_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='catalogitem',
            old_name='os_language',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='catalogitem',
            old_name='os_version',
            new_name='version',
        ),
        migrations.RenameField(
            model_name='catalogitem',
            old_name='os_version_scheme',
            new_name='version_scheme',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='os_description',
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='description',
            field=models.CharField(default='description', help_text='Item description', max_length=100, verbose_name='Description'),
            preserve_default=False,
        ),
    ]
