# Generated by Django 3.2.8 on 2021-11-16 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0011_auto_20211116_1019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalogitem',
            name='language',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='os_arch',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='os_edition',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='os_type',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='version',
        ),
        migrations.RemoveField(
            model_name='catalogitem',
            name='version_scheme',
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='os_edition_arch',
            field=models.CharField(choices=[('X86', 'x86'), ('AMD64', 'amd64'), ('ARMV8', 'ArmV8'), ('DARWIN_ARM64', 'darwin_arm64')], default='AMD64', help_text='The architecture of the OS', max_length=16, verbose_name='OS Architecture'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='os_edition_description',
            field=models.CharField(default='os description', help_text='Description of the OS', max_length=32, verbose_name='OS description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='os_edition_language',
            field=models.CharField(choices=[('ENGLISH', 'English'), ('FRENCH', 'French')], default='os edition language', help_text='The language of the item in the catalog', max_length=64, verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='os_edition_type',
            field=models.CharField(choices=[('WINDOWS', 'Windows'), ('APPLE', 'Apple'), ('LINUX', 'Linux'), ('BSD', 'BSD'), ('VMWARE', 'VMware'), ('STORAGE', 'Storage Appliances'), ('VIRTUALIZATION', 'Virtualization Appliances'), ('FIREWALL', 'Firewall Appliances'), ('FIRMWARE', 'Firmware and driver utilities'), ('RECOVERY', 'Recovery Tools'), ('OTHER', 'Other')], default='LINUX', help_text='The type of image', max_length=16, verbose_name='OS Type'),
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='os_edition_version',
            field=models.CharField(default='os edition ver', help_text='The version number of the item', max_length=32, verbose_name='Version Number'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='catalogitem',
            name='os_edition_version_scheme',
            field=models.CharField(default='os edition ver scheme', help_text='The version scheme of the OS', max_length=32, verbose_name='OS Version Scheme'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='catalogitem',
            name='os_edition_name',
            field=models.CharField(help_text='The edition of the OS', max_length=32, verbose_name='OS Edition'),
        ),
        migrations.DeleteModel(
            name='OsEdition',
        ),
    ]
