# Generated by Django 3.2.8 on 2021-11-26 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0012_auto_20211116_1503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogitem',
            name='sha256sum',
            field=models.CharField(help_text='SHA256 Checksum for this file', max_length=255, unique=True, verbose_name='SHA256 Checksum'),
        ),
    ]
