# Generated by Django 3.2.8 on 2021-11-26 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0013_alter_catalogitem_sha256sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remotecatalog',
            name='json_catalog',
            field=models.JSONField(default=dict, help_text='The JSON model as downloaded from the upstream', verbose_name='JSON catalog'),
        ),
    ]
