# Generated by Django 3.2.8 on 2021-12-01 05:31
import requests

from django.db import migrations

REMOTE_URL = "http://raph.info/dim.json"

def get_data():
    """ Get data from remote url
    """
    data = None
    try:
        res = requests.get(REMOTE_URL)
    except Execption as err:
        print(err)
    else:
        if res.status_code == 200:
            data = res.json()
    return data


def load_initial_data(apps, schema_editor   ):
    """ load initial data for remote catalog
    """
    remote_catalog = apps.get_model("isomanager", "RemoteCatalog")

    payload = {
                "catalog_name":"default",
                "json_catalog":get_data(),
                "version":"1.0",
                "auto_update":True,
                "priority":"1",
                "remote_url":REMOTE_URL
            }
    remote_catalog.objects.create(**payload)


def reverse_func(apps, schema_editor):
    """reverse the migration
    """
    remote_catalog = apps.get_model("isomanager", "RemoteCatalog")
    remote_catalog.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('isomanager', '0016_alter_remotecatalog_json_catalog'),
    ]

    operations = [
        migrations.RunPython(load_initial_data, reverse_func)
    ]
